name: delivery
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  geolocator: ^12.0.0
  http: ^1.2.2
  http_parser: ^4.0.0 
  image_picker: ^0.8.7+1
  google_maps_flutter: ^2.9.0  
  cupertino_icons: ^1.0.8
  permission_handler: ^10.2.0
  latlong2: ^0.9.1
  get: ^4.6.6 
  geolocator_android: 4.5.5
  flutter_map: ^7.0.2
  geocoding: ^2.2.2
  font_awesome_flutter: ^10.1.0
  
  firebase_core: ^2.24.2
  cloud_firestore: ^4.14.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/turbo.png
    - assets/images/tt.png
    - assets/config/